FROM node:18-alpine

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치 파일 복사
COPY ovis-core/package*.json ./

# 의존성 설치 - --legacy-peer-deps 옵션 추가
RUN npm install --legacy-peer-deps

# 소스 코드 복사
COPY ovis-core/ ./

# 환경 변수 설정
ENV REACT_APP_API_URL=/api
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV NODE_ENV=development
ENV PORT=3000
ENV HOST=0.0.0.0
ENV WDS_SOCKET_PORT=0

# 개발 서버의 웹소켓 오류 방지를 위한 환경 변수 설정
ENV DANGEROUSLY_DISABLE_HOST_CHECK=true
ENV FAST_REFRESH=false

# 개발 서버 실행을 위한 포트 노출
EXPOSE 3000

# 개발 서버 실행
CMD ["npm", "start"] 