FROM node:18-alpine as build

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치 파일 복사
COPY ovis-core/package*.json ./

# 의존성 설치
RUN npm install

# 소스 코드 복사
COPY ovis-core/ ./

# 생산용 빌드 생성
RUN npm run build

# 실행 단계
FROM nginx:alpine

# 빌드된 파일을 nginx로 복사
COPY --from=build /app/build /usr/share/nginx/html

# nginx 설정 추가
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 포트 설정
EXPOSE 80

# nginx 시작
CMD ["nginx", "-g", "daemon off;"] 