FROM node:18-alpine

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치 파일 복사
COPY ovis-core/package*.json ./

# 의존성 설치 - --legacy-peer-deps 옵션 추가
RUN npm install --legacy-peer-deps

# 소스 코드 복사
COPY ovis-core/ ./

# 환경 변수 설정
ENV REACT_APP_API_URL=http://ovis-app:3002
ENV NODE_OPTIONS="--max-old-space-size=4096"

# 빌드 대신 개발 서버 실행
EXPOSE 3000

# 개발 서버 실행
CMD ["npm", "start"] 